# coding: utf-8

"""
    HEP REST API

    The REST API for HEP protocol  # noqa: E501

    OpenAPI spec version: v1
    Contact: xiawu@zeuux.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import hep_rest
from models.dapp import Dapp  # noqa: E501
from hep_rest.rest import ApiException


class TestDapp(unittest.TestCase):
    """Dapp unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDapp(self):
        """Test Dapp"""
        # FIXME: construct object with mandatory attributes with example values
        # model = hep_rest.models.dapp.Dapp()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
