<?php
/**
 * DappTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * HEP REST API
 *
 * The REST API for HEP protocol
 *
 * OpenAPI spec version: v1
 * Contact: xiawu@zeuux.org
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.8
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * DappTest Class Doc Comment
 *
 * @category    Class
 * @description Dapp
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class DappTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Dapp"
     */
    public function testDapp()
    {
    }

    /**
     * Test attribute "dapp_key"
     */
    public function testPropertyDappKey()
    {
    }

    /**
     * Test attribute "protocol"
     */
    public function testPropertyProtocol()
    {
    }

    /**
     * Test attribute "version"
     */
    public function testPropertyVersion()
    {
    }

    /**
     * Test attribute "ts"
     */
    public function testPropertyTs()
    {
    }

    /**
     * Test attribute "nonce"
     */
    public function testPropertyNonce()
    {
    }

    /**
     * Test attribute "os"
     */
    public function testPropertyOs()
    {
    }

    /**
     * Test attribute "language"
     */
    public function testPropertyLanguage()
    {
    }

    /**
     * Test attribute "md5"
     */
    public function testPropertyMd5()
    {
    }

    /**
     * Test attribute "dapp_id"
     */
    public function testPropertyDappId()
    {
    }

    /**
     * Test attribute "dapp_name"
     */
    public function testPropertyDappName()
    {
    }

    /**
     * Test attribute "icon"
     */
    public function testPropertyIcon()
    {
    }

    /**
     * Test attribute "public_key"
     */
    public function testPropertyPublicKey()
    {
    }

    /**
     * Test attribute "package_name"
     */
    public function testPropertyPackageName()
    {
    }

    /**
     * Test attribute "bundle_id"
     */
    public function testPropertyBundleId()
    {
    }

    /**
     * Test attribute "schema"
     */
    public function testPropertySchema()
    {
    }

    /**
     * Test attribute "website"
     */
    public function testPropertyWebsite()
    {
    }

    /**
     * Test attribute "download_url"
     */
    public function testPropertyDownloadUrl()
    {
    }

    /**
     * Test attribute "deposit_contract_address"
     */
    public function testPropertyDepositContractAddress()
    {
    }

    /**
     * Test attribute "dapp_type"
     */
    public function testPropertyDappType()
    {
    }

    /**
     * Test attribute "dapp_category"
     */
    public function testPropertyDappCategory()
    {
    }

    /**
     * Test attribute "auth_login_callback"
     */
    public function testPropertyAuthLoginCallback()
    {
    }

    /**
     * Test attribute "pay_order_callback"
     */
    public function testPropertyPayOrderCallback()
    {
    }

    /**
     * Test attribute "proof_submit_callback"
     */
    public function testPropertyProofSubmitCallback()
    {
    }
}
