/*
 * HEP REST API
 * The REST API for HEP protocol
 *
 * OpenAPI spec version: v1
 * Contact: xiawu@zeuux.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.NewidResponse;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for NewidsApi
 */
@Ignore
public class NewidsApiTest {

    private final NewidsApi api = new NewidsApi();

    /**
     * 
     *
     * Retrieve the information by given NewID
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void newidsReadTest() throws ApiException {
        String newid = null;
        String dappKey = null;
        String protocol = null;
        String version = null;
        Integer ts = null;
        String nonce = null;
        String os = null;
        String language = null;
        String md5 = null;
        NewidResponse response = api.newidsRead(newid, dappKey, protocol, version, ts, nonce, os, language, md5);

        // TODO: test validations
    }
}
