/*
 * HEP REST API
 * The REST API for HEP protocol
 *
 * OpenAPI spec version: v1
 * Contact: xiawu@zeuux.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.CancelProofRequest;
import io.swagger.client.model.CancelProofResponse;
import io.swagger.client.model.CreateProofRequest;
import io.swagger.client.model.CreateProofResponse;
import io.swagger.client.model.UpdateProofRequest;
import io.swagger.client.model.UpdateProofResponse;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ProofsApi
 */
@Ignore
public class ProofsApiTest {

    private final ProofsApi api = new ProofsApi();

    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void proofsCreateTest() throws ApiException {
        CreateProofRequest body = null;
        CreateProofResponse response = api.proofsCreate(body);

        // TODO: test validations
    }
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void proofsDeleteTest() throws ApiException {
        CancelProofRequest body = null;
        String proofHash = null;
        CancelProofResponse response = api.proofsDelete(body, proofHash);

        // TODO: test validations
    }
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void proofsUpdateTest() throws ApiException {
        UpdateProofRequest body = null;
        String proofHash = null;
        UpdateProofResponse response = api.proofsUpdate(body, proofHash);

        // TODO: test validations
    }
}
