all:
	mvn install:install-file -Dfile=libs/utils-3.3.1-android.jar -DgroupId=com.newton -DartifactId=utils -Dversion=3.3.1 -Dpackaging=jar
	mvn install:install-file -Dfile=libs/core-3.3.1-android.jar -DgroupId=com.newton -DartifactId=core -Dversion=3.3.1 -Dpackaging=jar
	mvn install:install-file -Dfile=libs/crypto-3.3.1-android.jar -DgroupId=com.newton -DartifactId=crypto -Dversion=3.3.1 -Dpackaging=jar
