<?php
/**
 * OrderItem
 *
 * PHP version 5
 *
 * @category Class
 * @package  HepRestApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * HEP REST API
 *
 * The REST API for HEP protocol
 *
 * OpenAPI spec version: v1
 * Contact: xiawu@zeuux.org
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.7
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace HepRestApi\Model;

use \ArrayAccess;
use \HepRestApi\ObjectSerializer;

/**
 * OrderItem Class Doc Comment
 *
 * @category Class
 * @package  HepRestApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class OrderItem implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'OrderItem';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'order_item_number' => 'string',
        'ordered_item' => '\HepRestApi\Model\Thing',
        'order_item_quantity' => 'int',
        'price_currency' => 'string',
        'price' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'order_item_number' => null,
        'ordered_item' => null,
        'order_item_quantity' => null,
        'price_currency' => null,
        'price' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'order_item_number' => 'order_item_number',
        'ordered_item' => 'ordered_item',
        'order_item_quantity' => 'order_item_quantity',
        'price_currency' => 'price_currency',
        'price' => 'price'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'order_item_number' => 'setOrderItemNumber',
        'ordered_item' => 'setOrderedItem',
        'order_item_quantity' => 'setOrderItemQuantity',
        'price_currency' => 'setPriceCurrency',
        'price' => 'setPrice'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'order_item_number' => 'getOrderItemNumber',
        'ordered_item' => 'getOrderedItem',
        'order_item_quantity' => 'getOrderItemQuantity',
        'price_currency' => 'getPriceCurrency',
        'price' => 'getPrice'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['order_item_number'] = isset($data['order_item_number']) ? $data['order_item_number'] : null;
        $this->container['ordered_item'] = isset($data['ordered_item']) ? $data['ordered_item'] : null;
        $this->container['order_item_quantity'] = isset($data['order_item_quantity']) ? $data['order_item_quantity'] : null;
        $this->container['price_currency'] = isset($data['price_currency']) ? $data['price_currency'] : null;
        $this->container['price'] = isset($data['price']) ? $data['price'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['order_item_number'] === null) {
            $invalidProperties[] = "'order_item_number' can't be null";
        }
        if ((mb_strlen($this->container['order_item_number']) > 64)) {
            $invalidProperties[] = "invalid value for 'order_item_number', the character length must be smaller than or equal to 64.";
        }

        if ((mb_strlen($this->container['order_item_number']) < 1)) {
            $invalidProperties[] = "invalid value for 'order_item_number', the character length must be bigger than or equal to 1.";
        }

        if ($this->container['ordered_item'] === null) {
            $invalidProperties[] = "'ordered_item' can't be null";
        }
        if ($this->container['order_item_quantity'] === null) {
            $invalidProperties[] = "'order_item_quantity' can't be null";
        }
        if ($this->container['price_currency'] === null) {
            $invalidProperties[] = "'price_currency' can't be null";
        }
        if ((mb_strlen($this->container['price_currency']) > 64)) {
            $invalidProperties[] = "invalid value for 'price_currency', the character length must be smaller than or equal to 64.";
        }

        if ((mb_strlen($this->container['price_currency']) < 1)) {
            $invalidProperties[] = "invalid value for 'price_currency', the character length must be bigger than or equal to 1.";
        }

        if ($this->container['price'] === null) {
            $invalidProperties[] = "'price' can't be null";
        }
        if ((mb_strlen($this->container['price']) > 64)) {
            $invalidProperties[] = "invalid value for 'price', the character length must be smaller than or equal to 64.";
        }

        if ((mb_strlen($this->container['price']) < 1)) {
            $invalidProperties[] = "invalid value for 'price', the character length must be bigger than or equal to 1.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets order_item_number
     *
     * @return string
     */
    public function getOrderItemNumber()
    {
        return $this->container['order_item_number'];
    }

    /**
     * Sets order_item_number
     *
     * @param string $order_item_number The number of order item
     *
     * @return $this
     */
    public function setOrderItemNumber($order_item_number)
    {
        if ((mb_strlen($order_item_number) > 64)) {
            throw new \InvalidArgumentException('invalid length for $order_item_number when calling OrderItem., must be smaller than or equal to 64.');
        }
        if ((mb_strlen($order_item_number) < 1)) {
            throw new \InvalidArgumentException('invalid length for $order_item_number when calling OrderItem., must be bigger than or equal to 1.');
        }

        $this->container['order_item_number'] = $order_item_number;

        return $this;
    }

    /**
     * Gets ordered_item
     *
     * @return \HepRestApi\Model\Thing
     */
    public function getOrderedItem()
    {
        return $this->container['ordered_item'];
    }

    /**
     * Sets ordered_item
     *
     * @param \HepRestApi\Model\Thing $ordered_item ordered_item
     *
     * @return $this
     */
    public function setOrderedItem($ordered_item)
    {
        $this->container['ordered_item'] = $ordered_item;

        return $this;
    }

    /**
     * Gets order_item_quantity
     *
     * @return int
     */
    public function getOrderItemQuantity()
    {
        return $this->container['order_item_quantity'];
    }

    /**
     * Sets order_item_quantity
     *
     * @param int $order_item_quantity The quantity of order item
     *
     * @return $this
     */
    public function setOrderItemQuantity($order_item_quantity)
    {
        $this->container['order_item_quantity'] = $order_item_quantity;

        return $this;
    }

    /**
     * Gets price_currency
     *
     * @return string
     */
    public function getPriceCurrency()
    {
        return $this->container['price_currency'];
    }

    /**
     * Sets price_currency
     *
     * @param string $price_currency The symbol of fiat or digital token, such as USD, RMB, NEW,BTC,ETH.
     *
     * @return $this
     */
    public function setPriceCurrency($price_currency)
    {
        if ((mb_strlen($price_currency) > 64)) {
            throw new \InvalidArgumentException('invalid length for $price_currency when calling OrderItem., must be smaller than or equal to 64.');
        }
        if ((mb_strlen($price_currency) < 1)) {
            throw new \InvalidArgumentException('invalid length for $price_currency when calling OrderItem., must be bigger than or equal to 1.');
        }

        $this->container['price_currency'] = $price_currency;

        return $this;
    }

    /**
     * Gets price
     *
     * @return string
     */
    public function getPrice()
    {
        return $this->container['price'];
    }

    /**
     * Sets price
     *
     * @param string $price The amount of fiat or digital token, unit is the minimum unit of given fiat or digital token.
     *
     * @return $this
     */
    public function setPrice($price)
    {
        if ((mb_strlen($price) > 64)) {
            throw new \InvalidArgumentException('invalid length for $price when calling OrderItem., must be smaller than or equal to 64.');
        }
        if ((mb_strlen($price) < 1)) {
            throw new \InvalidArgumentException('invalid length for $price when calling OrderItem., must be bigger than or equal to 1.');
        }

        $this->container['price'] = $price;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


