<?php
/**
 * RetrieveDappDailyStatsResponse
 *
 * PHP version 5
 *
 * @category Class
 * @package  HepRestApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * HEP REST API
 *
 * The REST API for HEP protocol
 *
 * OpenAPI spec version: v1
 * Contact: xiawu@zeuux.org
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.7
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace HepRestApi\Model;

use \ArrayAccess;
use \HepRestApi\ObjectSerializer;

/**
 * RetrieveDappDailyStatsResponse Class Doc Comment
 *
 * @category Class
 * @package  HepRestApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class RetrieveDappDailyStatsResponse implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'RetrieveDappDailyStatsResponse';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'dapp_id' => 'string',
        'total_nf' => 'string',
        'total_tokens' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'dapp_id' => null,
        'total_nf' => null,
        'total_tokens' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'dapp_id' => 'dapp_id',
        'total_nf' => 'total_nf',
        'total_tokens' => 'total_tokens'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'dapp_id' => 'setDappId',
        'total_nf' => 'setTotalNf',
        'total_tokens' => 'setTotalTokens'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'dapp_id' => 'getDappId',
        'total_nf' => 'getTotalNf',
        'total_tokens' => 'getTotalTokens'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['dapp_id'] = isset($data['dapp_id']) ? $data['dapp_id'] : null;
        $this->container['total_nf'] = isset($data['total_nf']) ? $data['total_nf'] : null;
        $this->container['total_tokens'] = isset($data['total_tokens']) ? $data['total_tokens'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['dapp_id'] === null) {
            $invalidProperties[] = "'dapp_id' can't be null";
        }
        if ((mb_strlen($this->container['dapp_id']) > 64)) {
            $invalidProperties[] = "invalid value for 'dapp_id', the character length must be smaller than or equal to 64.";
        }

        if ((mb_strlen($this->container['dapp_id']) < 1)) {
            $invalidProperties[] = "invalid value for 'dapp_id', the character length must be bigger than or equal to 1.";
        }

        if ($this->container['total_nf'] === null) {
            $invalidProperties[] = "'total_nf' can't be null";
        }
        if ((mb_strlen($this->container['total_nf']) > 64)) {
            $invalidProperties[] = "invalid value for 'total_nf', the character length must be smaller than or equal to 64.";
        }

        if ((mb_strlen($this->container['total_nf']) < 1)) {
            $invalidProperties[] = "invalid value for 'total_nf', the character length must be bigger than or equal to 1.";
        }

        if ($this->container['total_tokens'] === null) {
            $invalidProperties[] = "'total_tokens' can't be null";
        }
        if ((mb_strlen($this->container['total_tokens']) > 64)) {
            $invalidProperties[] = "invalid value for 'total_tokens', the character length must be smaller than or equal to 64.";
        }

        if ((mb_strlen($this->container['total_tokens']) < 1)) {
            $invalidProperties[] = "invalid value for 'total_tokens', the character length must be bigger than or equal to 1.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets dapp_id
     *
     * @return string
     */
    public function getDappId()
    {
        return $this->container['dapp_id'];
    }

    /**
     * Sets dapp_id
     *
     * @param string $dapp_id The decentralized application ID
     *
     * @return $this
     */
    public function setDappId($dapp_id)
    {
        if ((mb_strlen($dapp_id) > 64)) {
            throw new \InvalidArgumentException('invalid length for $dapp_id when calling RetrieveDappDailyStatsResponse., must be smaller than or equal to 64.');
        }
        if ((mb_strlen($dapp_id) < 1)) {
            throw new \InvalidArgumentException('invalid length for $dapp_id when calling RetrieveDappDailyStatsResponse., must be bigger than or equal to 1.');
        }

        $this->container['dapp_id'] = $dapp_id;

        return $this;
    }

    /**
     * Gets total_nf
     *
     * @return string
     */
    public function getTotalNf()
    {
        return $this->container['total_nf'];
    }

    /**
     * Sets total_nf
     *
     * @param string $total_nf The total Newforce
     *
     * @return $this
     */
    public function setTotalNf($total_nf)
    {
        if ((mb_strlen($total_nf) > 64)) {
            throw new \InvalidArgumentException('invalid length for $total_nf when calling RetrieveDappDailyStatsResponse., must be smaller than or equal to 64.');
        }
        if ((mb_strlen($total_nf) < 1)) {
            throw new \InvalidArgumentException('invalid length for $total_nf when calling RetrieveDappDailyStatsResponse., must be bigger than or equal to 1.');
        }

        $this->container['total_nf'] = $total_nf;

        return $this;
    }

    /**
     * Gets total_tokens
     *
     * @return string
     */
    public function getTotalTokens()
    {
        return $this->container['total_tokens'];
    }

    /**
     * Sets total_tokens
     *
     * @param string $total_tokens The total number of tokens
     *
     * @return $this
     */
    public function setTotalTokens($total_tokens)
    {
        if ((mb_strlen($total_tokens) > 64)) {
            throw new \InvalidArgumentException('invalid length for $total_tokens when calling RetrieveDappDailyStatsResponse., must be smaller than or equal to 64.');
        }
        if ((mb_strlen($total_tokens) < 1)) {
            throw new \InvalidArgumentException('invalid length for $total_tokens when calling RetrieveDappDailyStatsResponse., must be bigger than or equal to 1.');
        }

        $this->container['total_tokens'] = $total_tokens;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


