# coding: utf-8

"""
    HEP REST API

    The REST API for HEP protocol  # noqa: E501

    OpenAPI spec version: v1
    Contact: xiawu@zeuux.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from models.pay_cache_request import PayCacheRequest  # noqa: E501
from swagger_client.rest import ApiException


class TestPayCacheRequest(unittest.TestCase):
    """PayCacheRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPayCacheRequest(self):
        """Test PayCacheRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.pay_cache_request.PayCacheRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
