# coding: utf-8

"""
    HEP REST API

    The REST API for HEP protocol  # noqa: E501

    OpenAPI spec version: v1
    Contact: xiawu@zeuux.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from models.update_proof_request import UpdateProofRequest  # noqa: E501
from swagger_client.rest import ApiException


class TestUpdateProofRequest(unittest.TestCase):
    """UpdateProofRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUpdateProofRequest(self):
        """Test UpdateProofRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.update_proof_request.UpdateProofRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
