# coding: utf-8

"""
    HEP REST API

    The REST API for HEP protocol  # noqa: E501

    OpenAPI spec version: v1
    Contact: xiawu@zeuux.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from api.newids_api import NewidsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestNewidsApi(unittest.TestCase):
    """NewidsApi unit test stubs"""

    def setUp(self):
        self.api = api.newids_api.NewidsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_newids_read(self):
        """Test case for newids_read

        """
        pass


if __name__ == '__main__':
    unittest.main()
