# coding: utf-8

"""
    HEP REST API

    The REST API for HEP protocol  # noqa: E501

    OpenAPI spec version: v1
    Contact: xiawu@zeuux.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from api.newnet_api import NewnetApi  # noqa: E501
from swagger_client.rest import ApiException


class TestNewnetApi(unittest.TestCase):
    """NewnetApi unit test stubs"""

    def setUp(self):
        self.api = api.newnet_api.NewnetApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_newnet_caches_auth_create(self):
        """Test case for newnet_caches_auth_create

        """
        pass

    def test_newnet_caches_auth_read(self):
        """Test case for newnet_caches_auth_read

        """
        pass

    def test_newnet_caches_pay_create(self):
        """Test case for newnet_caches_pay_create

        """
        pass

    def test_newnet_caches_pay_read(self):
        """Test case for newnet_caches_pay_read

        """
        pass


if __name__ == '__main__':
    unittest.main()
