# coding: utf-8

"""
    HEP REST API

    The REST API for HEP protocol  # noqa: E501

    OpenAPI spec version: v1
    Contact: xiawu@zeuux.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class CreatePayCacheResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'pay_hash': 'str'
    }

    attribute_map = {
        'pay_hash': 'pay_hash'
    }

    def __init__(self, pay_hash=None):  # noqa: E501
        """CreatePayCacheResponse - a model defined in Swagger"""  # noqa: E501
        self._pay_hash = None
        self.discriminator = None
        self.pay_hash = pay_hash

    @property
    def pay_hash(self):
        """Gets the pay_hash of this CreatePayCacheResponse.  # noqa: E501


        :return: The pay_hash of this CreatePayCacheResponse.  # noqa: E501
        :rtype: str
        """
        return self._pay_hash

    @pay_hash.setter
    def pay_hash(self, pay_hash):
        """Sets the pay_hash of this CreatePayCacheResponse.


        :param pay_hash: The pay_hash of this CreatePayCacheResponse.  # noqa: E501
        :type: str
        """
        if pay_hash is None:
            raise ValueError("Invalid value for `pay_hash`, must not be `None`")  # noqa: E501

        self._pay_hash = pay_hash

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CreatePayCacheResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CreatePayCacheResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
