<?php
/**
 * NewidsApi
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * HEP REST API
 *
 * The REST API for HEP protocol
 *
 * OpenAPI spec version: v1
 * Contact: xiawu@zeuux.org
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.8
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Swagger\Client\ApiException;
use Swagger\Client\Configuration;
use Swagger\Client\HeaderSelector;
use Swagger\Client\ObjectSerializer;

/**
 * NewidsApi Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class NewidsApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation newidsRead
     *
     * @param  string $newid newid (required)
     * @param  string $dapp_key The decentralized application access key (required)
     * @param  string $protocol The protocol name. default is &#x27;HEP&#x27;. (required)
     * @param  string $version The protocol version such as &#x27;1.0&#x27; (required)
     * @param  int $ts The current timestamp (required)
     * @param  string $nonce The random string or auto-increment sequence (required)
     * @param  string $os The operating system of client such as ios, android, dweb,etc. (required)
     * @param  string $language The i18n language code such as zh, en, etc. (required)
     * @param  string $md5 The HMAC authentication md5 checksum (required)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Swagger\Client\Model\NewidResponse
     */
    public function newidsRead($newid, $dapp_key, $protocol, $version, $ts, $nonce, $os, $language, $md5)
    {
        list($response) = $this->newidsReadWithHttpInfo($newid, $dapp_key, $protocol, $version, $ts, $nonce, $os, $language, $md5);
        return $response;
    }

    /**
     * Operation newidsReadWithHttpInfo
     *
     * @param  string $newid (required)
     * @param  string $dapp_key The decentralized application access key (required)
     * @param  string $protocol The protocol name. default is &#x27;HEP&#x27;. (required)
     * @param  string $version The protocol version such as &#x27;1.0&#x27; (required)
     * @param  int $ts The current timestamp (required)
     * @param  string $nonce The random string or auto-increment sequence (required)
     * @param  string $os The operating system of client such as ios, android, dweb,etc. (required)
     * @param  string $language The i18n language code such as zh, en, etc. (required)
     * @param  string $md5 The HMAC authentication md5 checksum (required)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Swagger\Client\Model\NewidResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function newidsReadWithHttpInfo($newid, $dapp_key, $protocol, $version, $ts, $nonce, $os, $language, $md5)
    {
        $returnType = '\Swagger\Client\Model\NewidResponse';
        $request = $this->newidsReadRequest($newid, $dapp_key, $protocol, $version, $ts, $nonce, $os, $language, $md5);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if (!in_array($returnType, ['string','integer','bool'])) {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\NewidResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation newidsReadAsync
     *
     * 
     *
     * @param  string $newid (required)
     * @param  string $dapp_key The decentralized application access key (required)
     * @param  string $protocol The protocol name. default is &#x27;HEP&#x27;. (required)
     * @param  string $version The protocol version such as &#x27;1.0&#x27; (required)
     * @param  int $ts The current timestamp (required)
     * @param  string $nonce The random string or auto-increment sequence (required)
     * @param  string $os The operating system of client such as ios, android, dweb,etc. (required)
     * @param  string $language The i18n language code such as zh, en, etc. (required)
     * @param  string $md5 The HMAC authentication md5 checksum (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function newidsReadAsync($newid, $dapp_key, $protocol, $version, $ts, $nonce, $os, $language, $md5)
    {
        return $this->newidsReadAsyncWithHttpInfo($newid, $dapp_key, $protocol, $version, $ts, $nonce, $os, $language, $md5)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation newidsReadAsyncWithHttpInfo
     *
     * 
     *
     * @param  string $newid (required)
     * @param  string $dapp_key The decentralized application access key (required)
     * @param  string $protocol The protocol name. default is &#x27;HEP&#x27;. (required)
     * @param  string $version The protocol version such as &#x27;1.0&#x27; (required)
     * @param  int $ts The current timestamp (required)
     * @param  string $nonce The random string or auto-increment sequence (required)
     * @param  string $os The operating system of client such as ios, android, dweb,etc. (required)
     * @param  string $language The i18n language code such as zh, en, etc. (required)
     * @param  string $md5 The HMAC authentication md5 checksum (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function newidsReadAsyncWithHttpInfo($newid, $dapp_key, $protocol, $version, $ts, $nonce, $os, $language, $md5)
    {
        $returnType = '\Swagger\Client\Model\NewidResponse';
        $request = $this->newidsReadRequest($newid, $dapp_key, $protocol, $version, $ts, $nonce, $os, $language, $md5);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'newidsRead'
     *
     * @param  string $newid (required)
     * @param  string $dapp_key The decentralized application access key (required)
     * @param  string $protocol The protocol name. default is &#x27;HEP&#x27;. (required)
     * @param  string $version The protocol version such as &#x27;1.0&#x27; (required)
     * @param  int $ts The current timestamp (required)
     * @param  string $nonce The random string or auto-increment sequence (required)
     * @param  string $os The operating system of client such as ios, android, dweb,etc. (required)
     * @param  string $language The i18n language code such as zh, en, etc. (required)
     * @param  string $md5 The HMAC authentication md5 checksum (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function newidsReadRequest($newid, $dapp_key, $protocol, $version, $ts, $nonce, $os, $language, $md5)
    {
        // verify the required parameter 'newid' is set
        if ($newid === null || (is_array($newid) && count($newid) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $newid when calling newidsRead'
            );
        }
        // verify the required parameter 'dapp_key' is set
        if ($dapp_key === null || (is_array($dapp_key) && count($dapp_key) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $dapp_key when calling newidsRead'
            );
        }
        // verify the required parameter 'protocol' is set
        if ($protocol === null || (is_array($protocol) && count($protocol) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $protocol when calling newidsRead'
            );
        }
        // verify the required parameter 'version' is set
        if ($version === null || (is_array($version) && count($version) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $version when calling newidsRead'
            );
        }
        // verify the required parameter 'ts' is set
        if ($ts === null || (is_array($ts) && count($ts) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $ts when calling newidsRead'
            );
        }
        // verify the required parameter 'nonce' is set
        if ($nonce === null || (is_array($nonce) && count($nonce) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $nonce when calling newidsRead'
            );
        }
        // verify the required parameter 'os' is set
        if ($os === null || (is_array($os) && count($os) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $os when calling newidsRead'
            );
        }
        // verify the required parameter 'language' is set
        if ($language === null || (is_array($language) && count($language) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $language when calling newidsRead'
            );
        }
        // verify the required parameter 'md5' is set
        if ($md5 === null || (is_array($md5) && count($md5) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $md5 when calling newidsRead'
            );
        }

        $resourcePath = '/newids/{newid}/';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($dapp_key !== null) {
            $queryParams['dapp_key'] = ObjectSerializer::toQueryValue($dapp_key);
        }
        // query params
        if ($protocol !== null) {
            $queryParams['protocol'] = ObjectSerializer::toQueryValue($protocol);
        }
        // query params
        if ($version !== null) {
            $queryParams['version'] = ObjectSerializer::toQueryValue($version);
        }
        // query params
        if ($ts !== null) {
            $queryParams['ts'] = ObjectSerializer::toQueryValue($ts);
        }
        // query params
        if ($nonce !== null) {
            $queryParams['nonce'] = ObjectSerializer::toQueryValue($nonce);
        }
        // query params
        if ($os !== null) {
            $queryParams['os'] = ObjectSerializer::toQueryValue($os);
        }
        // query params
        if ($language !== null) {
            $queryParams['language'] = ObjectSerializer::toQueryValue($language);
        }
        // query params
        if ($md5 !== null) {
            $queryParams['md5'] = ObjectSerializer::toQueryValue($md5);
        }

        // path params
        if ($newid !== null) {
            $resourcePath = str_replace(
                '{' . 'newid' . '}',
                ObjectSerializer::toPathValue($newid),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires HTTP basic authentication
        if ($this->config->getUsername() !== null || $this->config->getPassword() !== null) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
