<?php
/**
 * CreateProofRequestTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  HepRestApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * HEP REST API
 *
 * The REST API for HEP protocol
 *
 * OpenAPI spec version: v1
 * Contact: xiawu@zeuux.org
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.8
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace HepRestApi;

/**
 * CreateProofRequestTest Class Doc Comment
 *
 * @category    Class
 * @description CreateProofRequest
 * @package     HepRestApi
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CreateProofRequestTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "CreateProofRequest"
     */
    public function testCreateProofRequest()
    {
    }

    /**
     * Test attribute "dapp_key"
     */
    public function testPropertyDappKey()
    {
    }

    /**
     * Test attribute "protocol"
     */
    public function testPropertyProtocol()
    {
    }

    /**
     * Test attribute "version"
     */
    public function testPropertyVersion()
    {
    }

    /**
     * Test attribute "ts"
     */
    public function testPropertyTs()
    {
    }

    /**
     * Test attribute "nonce"
     */
    public function testPropertyNonce()
    {
    }

    /**
     * Test attribute "os"
     */
    public function testPropertyOs()
    {
    }

    /**
     * Test attribute "language"
     */
    public function testPropertyLanguage()
    {
    }

    /**
     * Test attribute "dapp_signature_method"
     */
    public function testPropertyDappSignatureMethod()
    {
    }

    /**
     * Test attribute "dapp_signature"
     */
    public function testPropertyDappSignature()
    {
    }

    /**
     * Test attribute "sign_type"
     */
    public function testPropertySignType()
    {
    }

    /**
     * Test attribute "signature"
     */
    public function testPropertySignature()
    {
    }

    /**
     * Test attribute "action"
     */
    public function testPropertyAction()
    {
    }

    /**
     * Test attribute "uuid"
     */
    public function testPropertyUuid()
    {
    }

    /**
     * Test attribute "dapp_id"
     */
    public function testPropertyDappId()
    {
    }

    /**
     * Test attribute "content"
     */
    public function testPropertyContent()
    {
    }
}
