<?php
/**
 * CurrentDataResponseTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  HepRestApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * HEP REST API
 *
 * The REST API for HEP protocol
 *
 * OpenAPI spec version: v1
 * Contact: xiawu@zeuux.org
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.7
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace HepRestApi;

/**
 * CurrentDataResponseTest Class Doc Comment
 *
 * @category    Class
 * @description CurrentDataResponse
 * @package     HepRestApi
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CurrentDataResponseTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "CurrentDataResponse"
     */
    public function testCurrentDataResponse()
    {
    }

    /**
     * Test attribute "start_timestamp"
     */
    public function testPropertyStartTimestamp()
    {
    }

    /**
     * Test attribute "end_timestamp"
     */
    public function testPropertyEndTimestamp()
    {
    }

    /**
     * Test attribute "remaining_days"
     */
    public function testPropertyRemainingDays()
    {
    }

    /**
     * Test attribute "locked_days"
     */
    public function testPropertyLockedDays()
    {
    }

    /**
     * Test attribute "minted_days"
     */
    public function testPropertyMintedDays()
    {
    }

    /**
     * Test attribute "collected_tokens"
     */
    public function testPropertyCollectedTokens()
    {
    }

    /**
     * Test attribute "collect_status"
     */
    public function testPropertyCollectStatus()
    {
    }

    /**
     * Test attribute "can_collect_tokens"
     */
    public function testPropertyCanCollectTokens()
    {
    }

    /**
     * Test attribute "in_minting_gravity"
     */
    public function testPropertyInMintingGravity()
    {
    }

    /**
     * Test attribute "current_minting_stage"
     */
    public function testPropertyCurrentMintingStage()
    {
    }

    /**
     * Test attribute "current_collect_stage"
     */
    public function testPropertyCurrentCollectStage()
    {
    }

    /**
     * Test attribute "total_minting_stages"
     */
    public function testPropertyTotalMintingStages()
    {
    }

    /**
     * Test attribute "released_tokens"
     */
    public function testPropertyReleasedTokens()
    {
    }

    /**
     * Test attribute "locked_tokens"
     */
    public function testPropertyLockedTokens()
    {
    }

    /**
     * Test attribute "total_mint_amount"
     */
    public function testPropertyTotalMintAmount()
    {
    }

    /**
     * Test attribute "total_exchange_tokens"
     */
    public function testPropertyTotalExchangeTokens()
    {
    }
}
