<?php
/**
 * RetrieveOracleResponseTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  HepRestApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * HEP REST API
 *
 * The REST API for HEP protocol
 *
 * OpenAPI spec version: v1
 * Contact: xiawu@zeuux.org
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.8
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace HepRestApi;

/**
 * RetrieveOracleResponseTest Class Doc Comment
 *
 * @category    Class
 * @description RetrieveOracleResponse
 * @package     HepRestApi
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class RetrieveOracleResponseTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "RetrieveOracleResponse"
     */
    public function testRetrieveOracleResponse()
    {
    }

    /**
     * Test attribute "oracle_id"
     */
    public function testPropertyOracleId()
    {
    }

    /**
     * Test attribute "oracle_name"
     */
    public function testPropertyOracleName()
    {
    }

    /**
     * Test attribute "public_key"
     */
    public function testPropertyPublicKey()
    {
    }
}
