/*
 * HEP REST API
 * The REST API for HEP protocol
 *
 * OpenAPI spec version: v1
 * Contact: xiawu@zeuux.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.AuthCacheRequest;
import io.swagger.client.model.AuthCacheResponse;
import io.swagger.client.model.CancelProofRequest;
import io.swagger.client.model.CancelProofResponse;
import io.swagger.client.model.CreateAuthCacheResponse;
import io.swagger.client.model.CreatePayCacheResponse;
import io.swagger.client.model.CreateProofRequest;
import io.swagger.client.model.CreateProofResponse;
import io.swagger.client.model.Dapp;
import io.swagger.client.model.NewidResponse;
import io.swagger.client.model.PayCacheRequest;
import io.swagger.client.model.PayCacheResponse;
import io.swagger.client.model.UpdateProofRequest;
import io.swagger.client.model.UpdateProofResponse;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for RestApi
 */
@Ignore
public class RestApiTest {

    private final RestApi api = new RestApi();

    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void restDappsReadTest() throws ApiException {
        String dappId = null;
        String version = null;
        String dappKey = null;
        String protocol = null;
        String version2 = null;
        Integer ts = null;
        String nonce = null;
        String os = null;
        String language = null;
        String md5 = null;
        Dapp response = api.restDappsRead(dappId, version, dappKey, protocol, version2, ts, nonce, os, language, md5);

        // TODO: test validations
    }
    /**
     * 
     *
     * Retrieve the information by given NewID
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void restNewidsReadTest() throws ApiException {
        String newid = null;
        String version = null;
        String dappKey = null;
        String protocol = null;
        String version2 = null;
        Integer ts = null;
        String nonce = null;
        String os = null;
        String language = null;
        String md5 = null;
        NewidResponse response = api.restNewidsRead(newid, version, dappKey, protocol, version2, ts, nonce, os, language, md5);

        // TODO: test validations
    }
    /**
     * 
     *
     * Caches the authentication request
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void restNewnetCachesAuthCreateTest() throws ApiException {
        AuthCacheRequest body = null;
        String version = null;
        CreateAuthCacheResponse response = api.restNewnetCachesAuthCreate(body, version);

        // TODO: test validations
    }
    /**
     * 
     *
     * Get the authentication information by given request hash.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void restNewnetCachesAuthReadTest() throws ApiException {
        String authHash = null;
        String version = null;
        String dappKey = null;
        String protocol = null;
        String version2 = null;
        Integer ts = null;
        String nonce = null;
        String os = null;
        String language = null;
        String md5 = null;
        AuthCacheResponse response = api.restNewnetCachesAuthRead(authHash, version, dappKey, protocol, version2, ts, nonce, os, language, md5);

        // TODO: test validations
    }
    /**
     * 
     *
     * Cache the pay request
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void restNewnetCachesPayCreateTest() throws ApiException {
        PayCacheRequest body = null;
        String version = null;
        CreatePayCacheResponse response = api.restNewnetCachesPayCreate(body, version);

        // TODO: test validations
    }
    /**
     * 
     *
     * Retrieve the pay information by given pay hash.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void restNewnetCachesPayReadTest() throws ApiException {
        String payHash = null;
        String version = null;
        String dappKey = null;
        String protocol = null;
        String version2 = null;
        Integer ts = null;
        String nonce = null;
        String os = null;
        String language = null;
        String md5 = null;
        PayCacheResponse response = api.restNewnetCachesPayRead(payHash, version, dappKey, protocol, version2, ts, nonce, os, language, md5);

        // TODO: test validations
    }
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void restProofsCreateTest() throws ApiException {
        CreateProofRequest body = null;
        String version = null;
        CreateProofResponse response = api.restProofsCreate(body, version);

        // TODO: test validations
    }
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void restProofsDeleteTest() throws ApiException {
        CancelProofRequest body = null;
        String proofHash = null;
        String version = null;
        CancelProofResponse response = api.restProofsDelete(body, proofHash, version);

        // TODO: test validations
    }
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void restProofsUpdateTest() throws ApiException {
        UpdateProofRequest body = null;
        String proofHash = null;
        String version = null;
        UpdateProofResponse response = api.restProofsUpdate(body, proofHash, version);

        // TODO: test validations
    }
}
