<?php
/**
 * RestApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * HEP REST API
 *
 * The REST API for HEP protocol
 *
 * OpenAPI spec version: v1
 * Contact: xiawu@zeuux.org
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.8
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;

/**
 * RestApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class RestApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for restDappsRead
     *
     * .
     *
     */
    public function testRestDappsRead()
    {
    }

    /**
     * Test case for restNewidsRead
     *
     * .
     *
     */
    public function testRestNewidsRead()
    {
    }

    /**
     * Test case for restNewnetCachesAuthCreate
     *
     * .
     *
     */
    public function testRestNewnetCachesAuthCreate()
    {
    }

    /**
     * Test case for restNewnetCachesAuthRead
     *
     * .
     *
     */
    public function testRestNewnetCachesAuthRead()
    {
    }

    /**
     * Test case for restNewnetCachesPayCreate
     *
     * .
     *
     */
    public function testRestNewnetCachesPayCreate()
    {
    }

    /**
     * Test case for restNewnetCachesPayRead
     *
     * .
     *
     */
    public function testRestNewnetCachesPayRead()
    {
    }

    /**
     * Test case for restProofsCreate
     *
     * .
     *
     */
    public function testRestProofsCreate()
    {
    }

    /**
     * Test case for restProofsDelete
     *
     * .
     *
     */
    public function testRestProofsDelete()
    {
    }
}
